# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Sat May  2 22:14:19 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(16)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs_nodes = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabs_nodes.setObjectName("tabs_nodes")
        self.tab_directory = QtWidgets.QWidget()
        self.tab_directory.setObjectName("tab_directory")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_directory)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vfs_dir_widget = VfsDirWidget(self.tab_directory)
        self.vfs_dir_widget.setObjectName("vfs_dir_widget")
        self.horizontalLayout.addWidget(self.vfs_dir_widget)
        self.tabs_nodes.addTab(self.tab_directory, "")
        self.tab_non_mapped_list = QtWidgets.QWidget()
        self.tab_non_mapped_list.setObjectName("tab_non_mapped_list")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_non_mapped_list)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vfs_node_widget_non_mapped = VfsNodeTableWidget(self.tab_non_mapped_list)
        self.vfs_node_widget_non_mapped.setObjectName("vfs_node_widget_non_mapped")
        self.horizontalLayout_2.addWidget(self.vfs_node_widget_non_mapped)
        self.tabs_nodes.addTab(self.tab_non_mapped_list, "")
        self.tab_raw_list = QtWidgets.QWidget()
        self.tab_raw_list.setObjectName("tab_raw_list")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_raw_list)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vfs_node_widget = VfsNodeTableWidget(self.tab_raw_list)
        self.vfs_node_widget.setObjectName("vfs_node_widget")
        self.horizontalLayout_3.addWidget(self.vfs_node_widget)
        self.tabs_nodes.addTab(self.tab_raw_list, "")
        self.verticalLayout.addWidget(self.tabs_nodes)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filter_label = QtWidgets.QLabel(self.layoutWidget)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_4.addWidget(self.filter_label)
        self.filter_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filter_edit.setObjectName("filter_edit")
        self.horizontalLayout_4.addWidget(self.filter_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vhash_to_vpath_label = QtWidgets.QLabel(self.layoutWidget)
        self.vhash_to_vpath_label.setObjectName("vhash_to_vpath_label")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_label)
        self.vhash_to_vpath_in_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.vhash_to_vpath_in_edit.setObjectName("vhash_to_vpath_in_edit")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_in_edit)
        self.vhash_to_vpath_out_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.vhash_to_vpath_out_edit.setReadOnly(True)
        self.vhash_to_vpath_out_edit.setObjectName("vhash_to_vpath_out_edit")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_out_edit)
        self.horizontalLayout_5.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabs_control = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabs_control.setObjectName("tabs_control")
        self.tab_extract = QtWidgets.QWidget()
        self.tab_extract.setObjectName("tab_extract")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_extract)
        self.gridLayout.setObjectName("gridLayout")
        self.chkbx_export_text_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_text_extract.setObjectName("chkbx_export_text_extract")
        self.gridLayout.addWidget(self.chkbx_export_text_extract, 1, 0, 1, 1)
        self.chkbx_export_contents_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_contents_extract.setObjectName("chkbx_export_contents_extract")
        self.gridLayout.addWidget(self.chkbx_export_contents_extract, 5, 0, 1, 1)
        self.bt_extract = QtWidgets.QPushButton(self.tab_extract)
        self.bt_extract.setObjectName("bt_extract")
        self.gridLayout.addWidget(self.bt_extract, 0, 1, 1, 1)
        self.chkbx_export_raw_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_raw_extract.setObjectName("chkbx_export_raw_extract")
        self.gridLayout.addWidget(self.chkbx_export_raw_extract, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.chkbx_export_processed_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_processed_extract.setObjectName("chkbx_export_processed_extract")
        self.gridLayout.addWidget(self.chkbx_export_processed_extract, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.tabs_control.addTab(self.tab_extract, "")
        self.tab_modding = QtWidgets.QWidget()
        self.tab_modding.setObjectName("tab_modding")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_modding)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chkbx_export_contents_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_contents_mods.setObjectName("chkbx_export_contents_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_contents_mods, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.bt_mod_build = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_build.setObjectName("bt_mod_build")
        self.gridLayout_3.addWidget(self.bt_mod_build, 1, 1, 1, 1)
        self.chkbx_export_raw_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_raw_mods.setObjectName("chkbx_export_raw_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_raw_mods, 0, 0, 1, 1)
        self.bt_mod_prep = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_prep.setObjectName("bt_mod_prep")
        self.gridLayout_3.addWidget(self.bt_mod_prep, 0, 1, 1, 1)
        self.chkbx_export_processed_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_processed_mods.setObjectName("chkbx_export_processed_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_processed_mods, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.tabs_control.addTab(self.tab_modding, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chkbx_export_save_to_one_dir = QtWidgets.QCheckBox(self.tab_2)
        self.chkbx_export_save_to_one_dir.setObjectName("chkbx_export_save_to_one_dir")
        self.gridLayout_2.addWidget(self.chkbx_export_save_to_one_dir, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.bt_extract_gltf_3d = QtWidgets.QPushButton(self.tab_2)
        self.bt_extract_gltf_3d.setObjectName("bt_extract_gltf_3d")
        self.gridLayout_2.addWidget(self.bt_extract_gltf_3d, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)
        self.tabs_control.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabs_control)
        self.verticalLayout.setStretch(0, 1)
        self.data_view = DataViewWidget(self.splitter)
        self.data_view.setObjectName("data_view")
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_project_new = QtWidgets.QAction(MainWindow)
        self.action_project_new.setObjectName("action_project_new")
        self.action_project_open = QtWidgets.QAction(MainWindow)
        self.action_project_open.setObjectName("action_project_open")
        self.action_external_add = QtWidgets.QAction(MainWindow)
        self.action_external_add.setObjectName("action_external_add")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_make_web_map = QtWidgets.QAction(MainWindow)
        self.action_make_web_map.setObjectName("action_make_web_map")
        self.action_file_gz_open = QtWidgets.QAction(MainWindow)
        self.action_file_gz_open.setObjectName("action_file_gz_open")
        self.menu_File.addAction(self.action_project_new)
        self.menu_File.addAction(self.action_project_open)
        self.menu_File.addAction(self.action_file_gz_open)
        self.menu_File.addAction(self.action_external_add)
        self.menu_File.addAction(self.action_exit)
        self.menu_Tools.addAction(self.action_make_web_map)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_nodes.setCurrentIndex(0)
        self.tabs_control.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tabs_nodes.setTabText(self.tabs_nodes.indexOf(self.tab_directory), QtWidgets.QApplication.translate("MainWindow", "Directory", None, -1))
        self.tabs_nodes.setTabText(self.tabs_nodes.indexOf(self.tab_non_mapped_list), QtWidgets.QApplication.translate("MainWindow", "Non-Mapped List", None, -1))
        self.tabs_nodes.setTabText(self.tabs_nodes.indexOf(self.tab_raw_list), QtWidgets.QApplication.translate("MainWindow", "Raw List", None, -1))
        self.filter_label.setText(QtWidgets.QApplication.translate("MainWindow", "Filter (Python Expression Syntax)", None, -1))
        self.filter_edit.setText(QtWidgets.QApplication.translate("MainWindow", ".*", None, -1))
        self.vhash_to_vpath_label.setText(QtWidgets.QApplication.translate("MainWindow", "VHash -> VPath", None, -1))
        self.vhash_to_vpath_in_edit.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.chkbx_export_text_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Text", None, -1))
        self.chkbx_export_contents_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export Contents", None, -1))
        self.bt_extract.setText(QtWidgets.QApplication.translate("MainWindow", "EXTRACT", None, -1))
        self.chkbx_export_raw_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export Raw Files", None, -1))
        self.chkbx_export_processed_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Processed", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_extract), QtWidgets.QApplication.translate("MainWindow", "Extract", None, -1))
        self.chkbx_export_contents_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export Contents", None, -1))
        self.bt_mod_build.setText(QtWidgets.QApplication.translate("MainWindow", "Build Modded Files", None, -1))
        self.chkbx_export_raw_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export Raw Files", None, -1))
        self.bt_mod_prep.setText(QtWidgets.QApplication.translate("MainWindow", "Extract For Modding", None, -1))
        self.chkbx_export_processed_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Processed", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_modding), QtWidgets.QApplication.translate("MainWindow", "Modding", None, -1))
        self.chkbx_export_save_to_one_dir.setText(QtWidgets.QApplication.translate("MainWindow", "Save To One Directory", None, -1))
        self.bt_extract_gltf_3d.setText(QtWidgets.QApplication.translate("MainWindow", "EXPORT 3D/GLTF2", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "3d/GLTF2", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_Edit.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Edit", None, -1))
        self.menu_Tools.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Tools", None, -1))
        self.action_project_new.setText(QtWidgets.QApplication.translate("MainWindow", "&New Project...", None, -1))
        self.action_project_open.setText(QtWidgets.QApplication.translate("MainWindow", "&Open Project...", None, -1))
        self.action_external_add.setText(QtWidgets.QApplication.translate("MainWindow", "&Add External...", None, -1))
        self.action_exit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, -1))
        self.action_exit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_make_web_map.setText(QtWidgets.QApplication.translate("MainWindow", "Make &Web Map...", None, -1))
        self.action_file_gz_open.setText(QtWidgets.QApplication.translate("MainWindow", "Open GenZero File...", None, -1))

from .vfsdirwidget import VfsDirWidget
from .vfsnodetablewidget import VfsNodeTableWidget
from .dataviewwidget import DataViewWidget
