# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Sun Nov 15 11:38:18 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(16)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs_nodes = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabs_nodes.setTabsClosable(True)
        self.tabs_nodes.setObjectName("tabs_nodes")
        self.verticalLayout.addWidget(self.tabs_nodes)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filter_label = QtWidgets.QLabel(self.layoutWidget)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_4.addWidget(self.filter_label)
        self.filter_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filter_edit.setText("")
        self.filter_edit.setObjectName("filter_edit")
        self.horizontalLayout_4.addWidget(self.filter_edit)
        self.filter_set_bt = QtWidgets.QPushButton(self.layoutWidget)
        self.filter_set_bt.setObjectName("filter_set_bt")
        self.horizontalLayout_4.addWidget(self.filter_set_bt)
        self.filter_clear_bt = QtWidgets.QPushButton(self.layoutWidget)
        self.filter_clear_bt.setObjectName("filter_clear_bt")
        self.horizontalLayout_4.addWidget(self.filter_clear_bt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabs_control = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabs_control.setObjectName("tabs_control")
        self.tab_extract = QtWidgets.QWidget()
        self.tab_extract.setObjectName("tab_extract")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_extract)
        self.gridLayout.setObjectName("gridLayout")
        self.chkbx_export_processed_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_processed_extract.setObjectName("chkbx_export_processed_extract")
        self.gridLayout.addWidget(self.chkbx_export_processed_extract, 4, 0, 1, 1)
        self.chkbx_export_text_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_text_extract.setObjectName("chkbx_export_text_extract")
        self.gridLayout.addWidget(self.chkbx_export_text_extract, 1, 0, 1, 1)
        self.bt_extract_folder_show = QtWidgets.QPushButton(self.tab_extract)
        self.bt_extract_folder_show.setText("")
        self.bt_extract_folder_show.setObjectName("bt_extract_folder_show")
        self.gridLayout.addWidget(self.bt_extract_folder_show, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.chkbx_export_contents_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_contents_extract.setObjectName("chkbx_export_contents_extract")
        self.gridLayout.addWidget(self.chkbx_export_contents_extract, 5, 0, 1, 1)
        self.bt_extract = QtWidgets.QPushButton(self.tab_extract)
        self.bt_extract.setObjectName("bt_extract")
        self.gridLayout.addWidget(self.bt_extract, 0, 2, 1, 1)
        self.chkbx_export_raw_extract = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_raw_extract.setObjectName("chkbx_export_raw_extract")
        self.gridLayout.addWidget(self.chkbx_export_raw_extract, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        self.chkbx_export_map = QtWidgets.QCheckBox(self.tab_extract)
        self.chkbx_export_map.setObjectName("chkbx_export_map")
        self.gridLayout.addWidget(self.chkbx_export_map, 6, 0, 1, 1)
        self.cmbbx_map_format = QtWidgets.QComboBox(self.tab_extract)
        self.cmbbx_map_format.setObjectName("cmbbx_map_format")
        self.cmbbx_map_format.addItem("")
        self.cmbbx_map_format.addItem("")
        self.cmbbx_map_format.addItem("")
        self.gridLayout.addWidget(self.cmbbx_map_format, 6, 2, 1, 1)
        self.tabs_control.addTab(self.tab_extract, "")
        self.tab_modding = QtWidgets.QWidget()
        self.tab_modding.setObjectName("tab_modding")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_modding)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chkbx_export_contents_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_contents_mods.setObjectName("chkbx_export_contents_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_contents_mods, 2, 0, 1, 1)
        self.bt_mod_build = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_build.setObjectName("bt_mod_build")
        self.gridLayout_3.addWidget(self.bt_mod_build, 1, 2, 1, 1)
        self.bt_mod_prep = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_prep.setObjectName("bt_mod_prep")
        self.gridLayout_3.addWidget(self.bt_mod_prep, 0, 2, 1, 1)
        self.bt_mod_build_folder_show = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_build_folder_show.setText("")
        self.bt_mod_build_folder_show.setObjectName("bt_mod_build_folder_show")
        self.gridLayout_3.addWidget(self.bt_mod_build_folder_show, 1, 1, 1, 1)
        self.chkbx_export_raw_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_raw_mods.setObjectName("chkbx_export_raw_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_raw_mods, 0, 0, 1, 1)
        self.bt_mod_folder_show = QtWidgets.QPushButton(self.tab_modding)
        self.bt_mod_folder_show.setText("")
        self.bt_mod_folder_show.setObjectName("bt_mod_folder_show")
        self.gridLayout_3.addWidget(self.bt_mod_folder_show, 0, 1, 1, 1)
        self.chkbx_export_processed_mods = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_export_processed_mods.setObjectName("chkbx_export_processed_mods")
        self.gridLayout_3.addWidget(self.chkbx_export_processed_mods, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.chkbx_mod_build_subset = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_mod_build_subset.setObjectName("chkbx_mod_build_subset")
        self.gridLayout_3.addWidget(self.chkbx_mod_build_subset, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 5, 0, 1, 1)
        self.chkbx_mod_do_not_build_archives = QtWidgets.QCheckBox(self.tab_modding)
        self.chkbx_mod_do_not_build_archives.setObjectName("chkbx_mod_do_not_build_archives")
        self.gridLayout_3.addWidget(self.chkbx_mod_do_not_build_archives, 4, 0, 1, 3)
        self.tabs_control.addTab(self.tab_modding, "")
        self.tab_3d_gltf2 = QtWidgets.QWidget()
        self.tab_3d_gltf2.setObjectName("tab_3d_gltf2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3d_gltf2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        self.bt_extract_gltf_3d = QtWidgets.QPushButton(self.tab_3d_gltf2)
        self.bt_extract_gltf_3d.setObjectName("bt_extract_gltf_3d")
        self.gridLayout_2.addWidget(self.bt_extract_gltf_3d, 0, 2, 1, 1)
        self.chkbx_export_3d_include_skeleton = QtWidgets.QCheckBox(self.tab_3d_gltf2)
        self.chkbx_export_3d_include_skeleton.setObjectName("chkbx_export_3d_include_skeleton")
        self.gridLayout_2.addWidget(self.chkbx_export_3d_include_skeleton, 1, 0, 1, 1)
        self.chkbx_export_save_to_one_dir = QtWidgets.QCheckBox(self.tab_3d_gltf2)
        self.chkbx_export_save_to_one_dir.setObjectName("chkbx_export_save_to_one_dir")
        self.gridLayout_2.addWidget(self.chkbx_export_save_to_one_dir, 0, 0, 1, 1)
        self.bt_extract_gltf_3d_folder_show = QtWidgets.QPushButton(self.tab_3d_gltf2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_extract_gltf_3d_folder_show.sizePolicy().hasHeightForWidth())
        self.bt_extract_gltf_3d_folder_show.setSizePolicy(sizePolicy)
        self.bt_extract_gltf_3d_folder_show.setText("")
        self.bt_extract_gltf_3d_folder_show.setObjectName("bt_extract_gltf_3d_folder_show")
        self.gridLayout_2.addWidget(self.bt_extract_gltf_3d_folder_show, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 1)
        self.lbl_texture_format = QtWidgets.QLabel(self.tab_3d_gltf2)
        self.lbl_texture_format.setObjectName("lbl_texture_format")
        self.gridLayout_2.addWidget(self.lbl_texture_format, 2, 0, 1, 1)
        self.cmbbx_texture_format = QtWidgets.QComboBox(self.tab_3d_gltf2)
        self.cmbbx_texture_format.setObjectName("cmbbx_texture_format")
        self.cmbbx_texture_format.addItem("")
        self.cmbbx_texture_format.addItem("")
        self.cmbbx_texture_format.addItem("")
        self.gridLayout_2.addWidget(self.cmbbx_texture_format, 2, 2, 1, 1)
        self.tabs_control.addTab(self.tab_3d_gltf2, "")
        self.tab_utils = QtWidgets.QWidget()
        self.tab_utils.setObjectName("tab_utils")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_utils)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vhash_to_vpath_label = QtWidgets.QLabel(self.tab_utils)
        self.vhash_to_vpath_label.setObjectName("vhash_to_vpath_label")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_label)
        self.vhash_to_vpath_in_edit = QtWidgets.QLineEdit(self.tab_utils)
        self.vhash_to_vpath_in_edit.setObjectName("vhash_to_vpath_in_edit")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_in_edit)
        self.vhash_to_vpath_out_edit = QtWidgets.QLineEdit(self.tab_utils)
        self.vhash_to_vpath_out_edit.setReadOnly(True)
        self.vhash_to_vpath_out_edit.setObjectName("vhash_to_vpath_out_edit")
        self.horizontalLayout_5.addWidget(self.vhash_to_vpath_out_edit)
        self.horizontalLayout_5.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.tabs_control.addTab(self.tab_utils, "")
        self.verticalLayout.addWidget(self.tabs_control)
        self.verticalLayout.setStretch(0, 1)
        self.data_view = DataViewWidget(self.splitter)
        self.data_view.setObjectName("data_view")
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 24))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_project_new = QtWidgets.QAction(MainWindow)
        self.action_project_new.setObjectName("action_project_new")
        self.action_project_open = QtWidgets.QAction(MainWindow)
        self.action_project_open.setObjectName("action_project_open")
        self.action_external_add = QtWidgets.QAction(MainWindow)
        self.action_external_add.setObjectName("action_external_add")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_make_web_map = QtWidgets.QAction(MainWindow)
        self.action_make_web_map.setObjectName("action_make_web_map")
        self.action_file_gz_open = QtWidgets.QAction(MainWindow)
        self.action_file_gz_open.setObjectName("action_file_gz_open")
        self.menu_File.addAction(self.action_project_new)
        self.menu_File.addAction(self.action_project_open)
        self.menu_File.addAction(self.action_file_gz_open)
        self.menu_File.addAction(self.action_external_add)
        self.menu_File.addAction(self.action_exit)
        self.menu_Tools.addAction(self.action_make_web_map)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_nodes.setCurrentIndex(-1)
        self.tabs_control.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.filter_label.setText(QtWidgets.QApplication.translate("MainWindow", "Filter (Python Expression Syntax)", None, -1))
        self.filter_set_bt.setText(QtWidgets.QApplication.translate("MainWindow", "Set", None, -1))
        self.filter_clear_bt.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.chkbx_export_processed_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Processed", None, -1))
        self.chkbx_export_text_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Text", None, -1))
        self.chkbx_export_contents_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export Contents", None, -1))
        self.bt_extract.setText(QtWidgets.QApplication.translate("MainWindow", "EXTRACT", None, -1))
        self.chkbx_export_raw_extract.setText(QtWidgets.QApplication.translate("MainWindow", "Export Raw Files", None, -1))
        self.chkbx_export_map.setText(QtWidgets.QApplication.translate("MainWindow", "Export Map", None, -1))
        self.cmbbx_map_format.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Full", None, -1))
        self.cmbbx_map_format.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Tiles", None, -1))
        self.cmbbx_map_format.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Full + Tiles", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_extract), QtWidgets.QApplication.translate("MainWindow", "Extract", None, -1))
        self.chkbx_export_contents_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export Contents", None, -1))
        self.bt_mod_build.setText(QtWidgets.QApplication.translate("MainWindow", "Build Modded Files", None, -1))
        self.bt_mod_prep.setText(QtWidgets.QApplication.translate("MainWindow", "Extract For Modding", None, -1))
        self.chkbx_export_raw_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export Raw Files", None, -1))
        self.chkbx_export_processed_mods.setText(QtWidgets.QApplication.translate("MainWindow", "Export As Processed", None, -1))
        self.chkbx_mod_build_subset.setText(QtWidgets.QApplication.translate("MainWindow", "Build Subset", None, -1))
        self.chkbx_mod_do_not_build_archives.setText(QtWidgets.QApplication.translate("MainWindow", "Do Not Build Archives", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_modding), QtWidgets.QApplication.translate("MainWindow", "Modding", None, -1))
        self.bt_extract_gltf_3d.setText(QtWidgets.QApplication.translate("MainWindow", "EXPORT 3D/GLTF2", None, -1))
        self.chkbx_export_3d_include_skeleton.setText(QtWidgets.QApplication.translate("MainWindow", "Include Skeleton", None, -1))
        self.chkbx_export_save_to_one_dir.setText(QtWidgets.QApplication.translate("MainWindow", "Save To One Directory", None, -1))
        self.lbl_texture_format.setText(QtWidgets.QApplication.translate("MainWindow", "Texture Format", None, -1))
        self.cmbbx_texture_format.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "dds", None, -1))
        self.cmbbx_texture_format.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "ddsc", None, -1))
        self.cmbbx_texture_format.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "png", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_3d_gltf2), QtWidgets.QApplication.translate("MainWindow", "3d/GLTF2", None, -1))
        self.vhash_to_vpath_label.setText(QtWidgets.QApplication.translate("MainWindow", "VHash -> VPath", None, -1))
        self.vhash_to_vpath_in_edit.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.tabs_control.setTabText(self.tabs_control.indexOf(self.tab_utils), QtWidgets.QApplication.translate("MainWindow", "Utils", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_Tools.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Tools", None, -1))
        self.action_project_new.setText(QtWidgets.QApplication.translate("MainWindow", "&New Project...", None, -1))
        self.action_project_open.setText(QtWidgets.QApplication.translate("MainWindow", "&Open Project...", None, -1))
        self.action_external_add.setText(QtWidgets.QApplication.translate("MainWindow", "&Add External...", None, -1))
        self.action_exit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, -1))
        self.action_exit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_make_web_map.setText(QtWidgets.QApplication.translate("MainWindow", "Make &Web Map...", None, -1))
        self.action_file_gz_open.setText(QtWidgets.QApplication.translate("MainWindow", "Open GenZero File...", None, -1))

from .dataviewwidget import DataViewWidget
